version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_4025Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: SIQACloudStreamsTests
  gitServerName: rimaSCName
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: rimabarman
  gitBranch: main
